# fly.toml file generated for worldlle on 2023-04-09T17:43:27+08:00

app = "worldlle"
kill_signal = "SIGTERM"
kill_timeout = 5
primary_region = "ams"
console_command = "/rails/bin/rails console"

[env]
REDIS_URL = "redis://default:8e1f488737c948a8a21161a43079a4f3@fly-whatsspoken-redis.upstash.io"

[processes]
app = "bin/rails server"
worker = "bundle exec sidekiq"

[http_service]
processes = ["app"]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1

[[statics]]
guest_path = "/rails/public"
url_prefix = "/"
